[BUGFIX] Fix failing regex validation
This fixes the error:

    Error: Add regex101.com link to that shows the regex in practise, so it will be easier to maintain in case of bug/extension in the future
    ------ -----------------------------------------------------------------------
     Line   php-domain/src/PhpDomain/MethodNameService.php
    ------ -----------------------------------------------------------------------
     13     Add regex101.com link to that shows the regex in practise, so it will
            be easier to maintain in case of bug/extension in the future
    ------ -----------------------------------------------------------------------